let DATA;const $=id=>document.getElementById(id);const imageMap=()=>Object.fromEntries(DATA.participants.map(p=>[p.name,p.shield]));const statMap=()=>Object.fromEntries(DATA.general.map(p=>[p.name,p]));
function teamCell(name){return `<div class="team"><img src="${imageMap()[name]||''}"><span class="name">${name}</span></div>`}
function go(id){document.querySelectorAll('.page,.navtab').forEach(x=>x.classList.remove('active'));$(id).classList.add('active');document.querySelector(`.navtab[data-section="${id}"]`)?.classList.add('active');scrollTo({top:document.querySelector('main').offsetTop-120,behavior:'smooth'})}
function renderCurrent(){const rows=[...DATA.participants].sort((a,b)=>b.points-a.points||a.id-b.id);$('updated').textContent=DATA.lastUpdated;$('currentRows').innerHTML=rows.map((p,i)=>`<div class="row"><span class="pos">${i+1}</span>${teamCell(p.name)}<span class="center">${p.played}</span><span class="num">${p.points}</span></div>`).join('')}
function sortedGeneral(mode){const x=[...DATA.general];if(mode==='points')return x.sort((a,b)=>b.points-a.points);if(mode==='titles')return x.sort((a,b)=>b.titles-a.titles||b.podiums-a.podiums);if(mode==='average')return x.sort((a,b)=>b.average-a.average);if(mode==='podiums')return x.sort((a,b)=>b.podiums-a.podiums||b.titles-a.titles);return x.sort((a,b)=>b.score-a.score)}
function renderGeneral(mode='ranking'){$('generalRows').innerHTML=sortedGeneral(mode).map((p,i)=>`<div class="general-row"><span class="pos">${i+1}</span>${teamCell(p.name)}<span class="center">${p.titles}</span><span class="center">${p.seconds}</span><span class="center">${p.thirds}</span><span class="center">${p.podiums}</span><span class="center">${p.top5}</span><span class="center">${p.seasons}</span><span class="num">${p.points.toLocaleString()}</span><span class="num">${p.average?p.average.toFixed(1):'—'}</span><span class="num">${p.score.toFixed(1)}</span></div>`).join('')}
function renderPlayers(filter=''){const stats=statMap();$('playerGrid').innerHTML=DATA.participants.filter(p=>p.name.toLowerCase().includes(filter.toLowerCase())).map(p=>{const s=stats[p.name]||{};return `<article class="player-card" data-player="${p.name}"><img src="${p.shield}"><h3>${p.name}</h3><small>${s.label||'Participante'}</small><p>${s.points?.toLocaleString()||0} puntos · ${s.podiums||0} podios</p></article>`}).join('');document.querySelectorAll('.player-card').forEach(c=>c.onclick=()=>openPlayer(c.dataset.player))}
function openPlayer(name){const p=DATA.participants.find(x=>x.name===name),s=statMap()[name]||{};$('modalContent').innerHTML=`<div class="profile-head"><img src="${p.shield}"><div><span class="eyebrow">${s.label||'PARTICIPANTE'}</span><h2>${name}</h2><p>${s.description||'Sin historial acumulado todavía.'}</p></div></div><div class="profile-stats"><article><b>${s.titles||0}</b><small>Títulos</small></article><article><b>${s.podiums||0}</b><small>Podios</small></article><article><b>${s.points?.toLocaleString()||0}</b><small>Puntos</small></article><article><b>${s.average?s.average.toFixed(1):'—'}</b><small>Promedio</small></article><article><b>${s.top5||0}</b><small>Top 5</small></article><article><b>${s.seasons||0}</b><small>Temporadas</small></article></div><div class="chart"><canvas id="playerChart" width="560" height="150"></canvas></div>`;$('playerModal').hidden=false;drawChart(p.evolution||[0,0,0,0,0])}
function drawChart(vals){const c=$('playerChart'),ctx=c.getContext('2d'),w=c.width,h=c.height,p=20;ctx.clearRect(0,0,w,h);ctx.strokeStyle='#28445f';for(let i=0;i<5;i++){let y=p+i*(h-2*p)/4;ctx.beginPath();ctx.moveTo(p,y);ctx.lineTo(w-p,y);ctx.stroke()}const max=Math.max(...vals,1);ctx.strokeStyle='#43d8d1';ctx.lineWidth=4;ctx.beginPath();vals.forEach((v,i)=>{let x=p+i*(w-2*p)/(vals.length-1),y=h-p-v/max*(h-2*p);i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke()}
function renderRecords(){$('recordGrid').innerHTML=DATA.records.map(r=>`<article class="record"><span>${r.title}</span><h3>${r.value}</h3><p>${r.player}</p></article>`).join('')}
function renderChampions(){$('groupGrid').innerHTML=DATA.champions.groups.map(g=>`<article class="group"><h3>${g.name}</h3>${g.teams.map((t,i)=>`<div class="group-team"><span class="pos">${i+1}</span><img src="${imageMap()[t]||''}"><b>${t}</b></div>`).join('')}</article>`).join('');$('bracket').innerHTML=DATA.champions.knockout.map(r=>`<article class="round"><h3>${r.round}</h3><div class="empty-match">Pendiente de clasificación</div><div class="empty-match">Pendiente de clasificación</div></article>`).join('')}
function renderNews(){const cards=DATA.news.map(n=>`<article class="news-card"><span>${n.date}</span><h3>${n.title}</h3><p>${n.text}</p></article>`).join('');$('newsGrid').innerHTML=cards;$('homeNews').innerHTML=cards}
async function init(){DATA=await(await fetch('data.json')).json();renderCurrent();renderGeneral();renderPlayers();renderRecords();renderChampions();renderNews();document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));document.querySelectorAll('.navtab').forEach(b=>b.onclick=()=>go(b.dataset.section));$('sortGeneral').onchange=e=>renderGeneral(e.target.value);$('playerSearch').oninput=e=>renderPlayers(e.target.value);$('closeModal').onclick=()=>$('playerModal').hidden=true;$('playerModal').onclick=e=>{if(e.target.id==='playerModal')$('playerModal').hidden=true};$('share').onclick=()=>navigator.share?navigator.share({title:'Cuban League',url:location.href}):navigator.clipboard.writeText(location.href);if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js')}init();