let DATA;const $=id=>document.getElementById(id);const imgMap=()=>Object.fromEntries(DATA.participants.map(p=>[p.name,p.shield]));
function teamCell(name){return `<div class="team"><img src="${imgMap()[name]||''}" alt=""><span class="name">${name}</span></div>`}
function renderCurrent(){const rows=[...DATA.participants].sort((a,b)=>b.points-a.points||a.id-b.id);$('updated').textContent=DATA.lastUpdated;$('currentRows').innerHTML=rows.map((p,i)=>`<div class="row"><span class="pos">${i+1}</span>${teamCell(p.name)}<span class="center">${p.played}</span><span class="num">${p.points}</span></div>`).join('')}
function renderSeasons(){$('seasonSelect').innerHTML=DATA.seasons.map(s=>`<option>${s.label}</option>`).join('');showSeason(DATA.seasons[0].id);$('seasonSelect').onchange=e=>showSeason(e.target.value)}
function showSeason(id){const s=DATA.seasons.find(x=>x.id===id);if(!s.results.length){$('seasonTable').hidden=true;$('seasonState').hidden=false;$('seasonState').innerHTML=`<h3>${s.label}</h3><p>La estructura está preparada, pero falta cargar la clasificación final de esta temporada: posición, participante y puntos.</p>`;return}$('seasonState').hidden=true;$('seasonTable').hidden=false;$('seasonTable').innerHTML=`<div class="thead current-grid"><span>#</span><span>Participante</span><span></span><span>Puntos</span></div>`+s.results.map(r=>`<div class="row"><span class="pos">${r.position}</span>${teamCell(r.name)}<span></span><span class="num">${r.points.toLocaleString()}</span></div>`).join('')}
function sortedGeneral(mode){const x=[...DATA.general];if(mode==='points')return x.sort((a,b)=>b.points-a.points);if(mode==='titles')return x.sort((a,b)=>b.titles-a.titles||b.podiums-a.podiums||b.points-a.points);if(mode==='average')return x.sort((a,b)=>b.average-a.average);if(mode==='podiums')return x.sort((a,b)=>b.podiums-a.podiums||b.titles-a.titles||b.points-a.points);return x.sort((a,b)=>b.score-a.score)}
function renderGeneral(mode='ranking'){$('generalRows').innerHTML=sortedGeneral(mode).map((p,i)=>`<div class="general-row"><span class="pos">${i+1}</span>${teamCell(p.name)}<span class="center">${p.titles}</span><span class="center">${p.seconds}</span><span class="center">${p.thirds}</span><span class="center">${p.podiums}</span><span class="center">${p.top5}</span><span class="center">${p.seasons}</span><span class="num">${p.points.toLocaleString()}</span><span class="num">${p.average?p.average.toFixed(1):'—'}</span><span class="num">${p.score.toFixed(1)}</span></div>`).join('')}
function renderPalmares(){$('palmaresCards').innerHTML=DATA.general.filter(p=>p.podiums>0).sort((a,b)=>b.titles-a.titles||b.seconds-a.seconds||b.thirds-a.thirds).map(p=>`<article class="profile">${teamCell(p.name)}<span>${p.label}</span><div class="stats"><b>${p.titles} títulos</b><b>${p.seconds} segundos</b><b>${p.thirds} terceros</b><b>${p.podiums} podios</b></div><p>${p.description}</p></article>`).join('')}
function renderAwards(){$('awardCards').innerHTML=DATA.awards.map(a=>`<article class="profile"><span>${a.title}</span><h3>${a.player}</h3><p>${a.text}</p></article>`).join('')}
async function init(){DATA=await(await fetch('data.json')).json();renderCurrent();renderSeasons();renderGeneral();renderPalmares();renderAwards();$('sortGeneral').onchange=e=>renderGeneral(e.target.value);document.querySelectorAll('.navtab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.navtab,.page').forEach(x=>x.classList.remove('active'));b.classList.add('active');$(b.dataset.section).classList.add('active')});$('share').onclick=()=>navigator.share?navigator.share({title:'Cuban League',url:location.href}):navigator.clipboard.writeText(location.href)}init();